config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/splash', to: 'splashes#index'
  root 'groups#index'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users do
    resources :groups do
      resources :entities
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :amount, presence: true, numericality: { only_integer: true }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user

  validates :name, :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups
  validates :name, presence: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  private

  def authenticate_user!
    if user_signed_in?
      super
    elsif request.original_fullpath != splash_path
      redirect_to splash_path
    end
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_entity, only: %i[show edit update destroy]

  # GET /entities or /entities.json
  def index
    @entities = Entity.all
  end

  # GET /entities/1 or /entities/1.json
  def show; end

  # GET /entities/new
  def new
    @entity = Entity.new
  end

  # GET /entities/1/edit
  def edit; end

  # POST /entities or /entities.json
  def create
    @entity = Entity.new(entity_params)
    @entity.user_id = current_user.id
    @entity.group_id = Group.find(params[:group_id]).id

    respond_to do |format|
      if @entity.save
        format.html do
          redirect_to user_group_path(current_user, params[:group_id]), notice: 'Entity was successfully created.'
        end
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entities/1 or /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to entity_url(@entity), notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1 or /entities/1.json
  def destroy
    @entity.destroy

    respond_to do |format|
      format.html { redirect_to user_group_entities_url, notice: 'Entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entity
    @entity = Entity.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entity_params
    params.require(:entity).permit(:user_id, :name, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
    @group = Group.find(params[:id])
    @entities = Entity.where(group_id: @group.id)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id

    respond_to do |format|
      if @group.save
        format.html { redirect_to user_group_url(current_user, @group), notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    Entity.where(group_id: @group.id).destroy_all
    @group.destroy

    respond_to do |format|
      format.html { redirect_to user_groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splashes_controller.rb
class SplashesController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    redirect_to user_groups_path(current_user.id)
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    redirect_to user_groups_path(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  def splash; end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entities/_entity.html.erb
<div id="<%= dom_id entity %>">
  <p>
    <strong>Name:</strong>
    <%= entity.name %>
  </p>

  <p><strong>Amount:</strong><%= entity.amount %>$</p>

</div>

app/views/entities/_form.html.erb
<%= form_with model: entity, url: user_group_entities_path, class: "form-for-entity" do |form| %>
  <% if entity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
        <% entity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :name, placeholder: "Name", class: "add-entity-name" %>

  <%= form.number_field :amount, placeholder: "Amount", class: "add-entity-amount" %>

  <%= form.submit "Add transaction", class: "add-entity-btn" %>
<% end %>

app/views/entities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Entities</h1>

<div id="entities">
  <% @entities.each do |entity| %>
    <%= render entity %>
  <% end %>
</div>

<%= link_to "New entity", new_user_group_entity_path %>

app/views/entities/new.html.erb
<%= render "form", entity: @entity %>

app/views/entities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @entity %>

<div>
  <%= link_to "Edit this entity", edit_user_group_entity_path(@entity) %> |
  <%= link_to "Back to entities", user_group_entities_path %>

  <%= button_to "Destroy this entity", user_group_entity_path(@entity), method: :delete %>
</div>

app/views/groups/_form.html.erb
<%= form_with model: group, url: "/users/#{current_user.id}/groups", class: "form-for-add-category" do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%# <div> %>
    <%= form.text_field :name, placeholder: "Name", class: "new-category-name-field" %>
  <%# </div> %>

  <%# <div> %>
    <%= form.text_field :icon, placeholder: "Type category icon name", class: "new-category-icon-field" %>
  <%# </div> %>

  <%# <div> %>
    <%= form.submit "Add Category", class: "add-category-btn" %>
  <%# </div> %>
<% end %>

app/views/groups/_group.html.erb
<a href="/users/<%=current_user.id%>/groups/<%= group.id%>" id="<%= dom_id group %>" class="category-card">
  <img src="https://source.unsplash.com/random/1920x1080/?<%=group.icon%>" />
  
  <p class="category-div-name">
    <%= group.name %>
  </p>

  <p class="total-amout-text">$<%=Entity.where(group_id: group.id).sum(:amount)%></p>

</a>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", user_group_path(current_user, params[:id]) %> |
  <%= link_to "Back to groups", user_groups_path %>
</div>

app/views/groups/index.html.erb
<div id="groups">
  <span class="total-amount-text">Total amount $<%= Entity.where(user_id: current_user.id).sum(:amount)%></span>
    <% if @groups.length == 0 %>
      <h2 class="no-items-yet-text">No groups yet😢</h2>
    <%end%>
  <% @groups.each do |group| %>
    <%= render group if group.user_id == current_user.id%>
  <% end %>
</div>

<div class="add-new-group-div">
  <%= link_to "NEW GROUP", new_user_group_path(current_user.id) %>
</div>

app/views/groups/new.html.erb
<%= render "form", group: @group %>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>


<div class="transactions-container-div">
  <% @entities.each do |i| %>
      <div class="transaction-div">
        <div>
          <span class="trans-name"><%= i.name %></span>
          <span class="trans-date"><%= i.created_at.strftime('%d %b %Y at %H:%M:%S')%></span>
        </div>
        <span><b>$<%= i.amount %></b></span>
      </div>
  <% end %>
</div>

<div id="transactions-container">
  <%= link_to "Edit this group", edit_user_group_path(@group) %>
  <%# <%= link_to "Back to groups", user_groups_path %>

  <%= button_to "Destroy this group", user_group_path, method: :delete %>
  <%= link_to "Add new transaction", new_user_group_entity_path(params[:user_id], params[:id]) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <% if request.path == "/users/sign_in" %>
        <a class="back" href="/splash"><i class="fa fa-angle-left"></i></a>
        <span class="navbar-text" style="flex: 0.560;">LOGIN</span>
      <% elsif request.path == "/users/sign_up" %>
        <a class="back" href="/splash"><i class="fa fa-angle-left"></i></a>
        <span class="navbar-text", style="flex: 0.560;">REGISTER</span>
      <% elsif request.path == "/users/#{params[:user_id]}/groups/#{params[:id]}" %>
        <a class="back" href="/users/<%=params[:user_id]%>/groups"><i class="fa fa-angle-left"></i></a>
        <span class="navbar-text">TRANSACTIONS</span>
      <% elsif request.path == "/splash" %>
        <span style="text-align: center; flex: 1; color: #D2E1EBFF;">WELCOME</span>
      <% elsif request.path == "/users/4/groups/26/entities/new" %>
        <a class="back" href="/users/<%=params[:user_id]%>/groups/<%= params[:group_id]%>"><i class="fa fa-angle-left"></i></a>
        <span style="text-align: center; flex: 1; color: #D2E1EBFF;">NEW TRANSACTION</span>
      <%else%>
        <a class="back" href="/users/sign_in"><i class="fa fa-angle-left"></i></a>
        <span class="navbar-text">CATEGORIES </span>
      <%end%>
      <%if user_signed_in? %>
        <%=link_to "SIGN OUT", destroy_user_session_path, class: "lolo", method: :delete %>
      <%end%>
    </nav>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/splashes/index.html.erb
<div class="splash-main">
  <h1>Budget Tracker</h1>
  <%= link_to "LOG IN",   new_user_session_path, class: "login-text" %>
  <%= link_to "SIGN UP", new_user_registration_path, class: "sign-up-text" %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>

app/views/users/splash.html.erb
<div class="splash-main">
  <h1>Budget Tracker</h1>
  <%= link_to "LOG IN",   new_user_session_path, class: "login-text" %>
  <%= link_to "SIGN UP", new_user_registration_path, class: "sign-up-text" %>
</div>